config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'register/form'

  post 'register/confirmation'

  post 'register/receipt'

  get 'register/index'

  get 'register/check'

  post 'register/check_details'

  resources :hostels
  root 'register#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hostel.rb
class Hostel < ApplicationRecord
end

app/models/register.rb
class Register < ActiveRecord::Base
validate :custom
private
def custom
  puts "Come Here"
  if params[:number_of_rooms].to_i > 10
    puts "||||||||||||||||"
    puts "Over"
    puts "||||||||||||||||  "
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    # def user_authentication!
    #              	unless user_signed_in?
    #                   redirect_to new_user_session_path, alert: "We are sorry. You do not have permission for that action."
    #               end
    #
    # end
end

app/controllers/hostels_controller.rb
class HostelsController < ApplicationController
  before_action :set_hostel, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!


  # GET /hostels
  # GET /hostels.json
  def index
    @hostels = Hostel.all
    @hostels.each do |h|
      puts h.data["hostel_name"]
    end
  end

  # GET /hostels/1
  # GET /hostels/1.json
  def show
  end

  # GET /hostels/new
  def new
    @hostel = Hostel.new
  end

  # GET /hostels/1/edit
  def edit
  end

  # POST /hostels
  # POST /hostels.json
  def create
    @hostel = Hostel.new(hostel_params)

    respond_to do |format|
      if @hostel.save
        format.html { redirect_to @hostel, notice: 'Hostel was successfully created.' }
        format.json { render :show, status: :created, location: @hostel }
      else
        format.html { render :new }
        format.json { render json: @hostel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hostels/1
  # PATCH/PUT /hostels/1.json
  def update
    respond_to do |format|
      if @hostel.update(hostel_params)
        format.html { redirect_to @hostel, notice: 'Hostel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hostel }
      else
        format.html { render :edit }
        format.json { render json: @hostel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hostels/1
  # DELETE /hostels/1.json
  def destroy
    @hostel.destroy
    respond_to do |format|
      format.html { redirect_to hostels_url, notice: 'Hostel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hostel
      @hostel = Hostel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hostel_params
      params.require(:hostel).permit(:mobile_no, :data, :otp, :otp_created_at, :otp_expired_at, :reg_number)
    end

end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
   # before_action :user_authentication!
   # before_action :user_authorization!
    # validates :volume_limits
  def index

  end

  def form

  end

  def registration

  end

  def checkd

  end

  def check_details
    @check_number=params[:check_registration_number]
    @hostels= Hostel.where(otp: @check_number)
      if @hostels.count < 1
        @error = "true"
        render "check"
      end
  end

  def confirmation
    $decision="false"
    $temp = "true"
      if params[:condition] != "receipt"
        $hostel_name= params[:hostel_name]
        $contact_number= params[:contact_number]
        $address= params[:address]
        $township= params[:township]
        $owner_name= params[:owner_name]
        $owner_nric= params[:owner_nric]
        $number_of_rooms= params[:number_of_rooms]
        $total_pax= params[:total_pax]
        $code = Random.rand(100000..999999).to_s
        puts "---------"
        puts $code
        puts "---------"
      else
          if $code == params[:confirm]
            $decision = "true"
            $temp=true
            $date = Date.today
            $hour = Time.now.strftime("%H")
            $min  = Time.now.strftime("%M")
            $sec  = Time.now.strftime("%S")
            $otp_create = $date.to_s + " " + $hour.to_s+":"+ $min.to_s + ":" + $sec.to_s
            puts $otp_create
            if( $min.to_i + 30) >= 60
              $hour = $hour.to_i + 1
              $min  =  ($min.to_i + 30) % 60
                if $min.to_i < 10
                  $min = "0" + $min.to_s
                end
            else
              $min = $min.to_i + 30
            end
            $otp_expire = $date.to_s + " " + $hour.to_s + ":" + $min.to_s + ":" + $sec.to_s
            puts $otp_expire
            Hostel.create(mobile_no: $contact_number,data:{"hostel_name": $hostel_name,contact_number: $contact_number,address: $address,township: $township, owner_name: $owner_name, owner_nric: $owner_nric, number_of_rooms: $number_of_rooms.to_i, total_pax: $total_pax.to_i} , otp: $code, otp_created_at: $otp_create, otp_expired_at: $otp_expire)
            render register_receipt_path
          else
            $temp="false"
          end
      end
  end

  def receipt

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hostels_helper.rb
module HostelsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/views/hostels/_form.html.erb
<%= form_for @hostel, :html => { :class => "form-horizontal hostel" } do |f| %>

  <% if @hostel.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@hostel.errors.count, "error") %> prohibited this hostel from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @hostel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :mobile_no, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mobile_no, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mobile_no) %>
  </div>
  <div class="form-group">
    <%= f.label :data, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :data, :class => 'form-control' %>
    </div>
    <%=f.error_span(:data) %>
  </div>
  <div class="form-group">
    <%= f.label :otp, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :otp, :class => 'form-control' %>
    </div>
    <%=f.error_span(:otp) %>
  </div>
  <div class="form-group">
    <%= f.label :otp_created_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :otp_created_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:otp_created_at) %>
  </div>
  <div class="form-group">
    <%= f.label :otp_expired_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :otp_expired_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:otp_expired_at) %>
  </div>
  <div class="form-group">
    <%= f.label :reg_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :reg_number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:reg_number) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                hostels_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/hostels/edit.html.erb
<%- model_class = Hostel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/hostels/index.html.erb
<%- model_class = Hostel -%>
<div class="container-fluid">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:mobile_no) %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:otp) %></th>
      <th><%= model_class.human_attribute_name(:otp_created_at) %></th>
      <th><%= model_class.human_attribute_name(:otp_expired_at) %></th>
      <th><%= model_class.human_attribute_name(:reg_number) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @hostels.each do |hostel| %>
      <tr>
        <td><%= link_to hostel.id, hostel_path(hostel) %></td>
        <td><%= hostel.mobile_no %></td>
        <td><%= hostel.data %></td>
        <td><%= hostel.otp %></td>
        <td><%= hostel.otp_created_at %></td>
        <td><%= hostel.otp_expired_at %></td>
        <td><%= hostel.reg_number %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      hostel_path(hostel), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_hostel_path(hostel), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      hostel_path(hostel),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/hostels/new.html.erb
<%- model_class = Hostel -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/hostels/show.html.erb
<%- model_class = Hostel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:mobile_no) %>:</strong></dt>
  <dd><%= @hostel.mobile_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data) %>:</strong></dt>
  <dd><%= @hostel.data %></dd>
  <dt><strong><%= model_class.human_attribute_name(:otp) %>:</strong></dt>
  <dd><%= @hostel.otp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:otp_created_at) %>:</strong></dt>
  <dd><%= @hostel.otp_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:otp_expired_at) %>:</strong></dt>
  <dd><%= @hostel.otp_expired_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reg_number) %>:</strong></dt>
  <dd><%= @hostel.reg_number %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              hostels_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_hostel_path(@hostel), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              hostel_path(@hostel),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('mylogo.png'), :rel => 'icon', :type => 'image/jpg' %>
    <title>HostelSelfRegistrationSystem</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    </style>
  </head>

  <body>
    <%= alert %>
    <%= yield %>
  </body>
</html>

app/views/register/check.html.erb
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
    <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'index', 'data-turbolinks-track': 'reload' %>
</head>
<body class="mybody">
  <%= form_tag(register_check_details_path, method: "post" , local:true, class: "myform" ) do |f|%>

    <div class="col-xl-4 col-lg-6 col-lg-offset-3 col-xl-offset-4">
      <h2><strong> Check Hostel Registration</strong></h2>
    </div>
    <% if @error== "true"%>
      <div class=" col-xl-4 col-lg-4 col-md-10 col-sm-10 col-lg-offset-4 col-xl-offset-4 col-md-offset-1 col-sm-offset-1 error ">
        <p >
            <h5>Your registration number is not correct<br>
                Please reenter your registration number or <br>
                <%= link_to "Register your hostel" ,register_form_path   %>  
            </h5>
        </p>
      </div>
    <%- end -%>
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
      <p>
        <%= label_tag :Please_Enter_Your_Registration_Number , nil, :class => 'floatLabel'%>
        <%= number_field_tag  :check_registration_number %>
      </p>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
      <%= submit_tag("Next",:class=>"mybtn",:style=>"font-size:14px;") %>
    </div>

    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <%- end -%>
</body>
</html>

app/views/register/confirmation.html.erb
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'index', 'data-turbolinks-track': 'reload' %>
</head>
<body class="mybody">
  <%= form_tag(register_confirmation_path, method: "post" , local:true, class: "myform" ) do |f|%>
    <div class="col-xl-4 col-lg-6 col-lg-offset-3 col-xl-offset-4" >
        <h2 ><strong>Check OTP Number</strong></h2>
    </div>

    <% if $temp == "false" %>
        <div class=" col-xl-4 col-lg-4 col-md-10 col-sm-10 col-lg-offset-4 col-xl-offset-4 col-md-offset-1 col-sm-offset-1 error ">
          <p >
              <h5>Your otp number is not correct<br>
                  Please reenter your otp number <br>
              </h5>
          </p>
        </div>
    <% end %>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
      <p>
        <%= label_tag :confirm_otp_number, nil, :class => 'floatLabel'%>
        <%=text_field_tag :confirm %>
      </p>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
  		<p>
        <%= label_tag :hostel_name, nil, :class => 'floatLabel'%>
        <%= text_field_tag  :hostel_name , $hostel_name, :readonly => true %>
  		</p>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
  		<p>
        <%= label_tag :address, nil, :class => 'floatLabel'%>
        <%= text_area_tag  :address, $address, :readonly => true,:class => "textarea" %>
  		</p>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
      <p>
        <%= label_tag :owner_name, nil, :class => 'floatLabel'%>
        <%= text_field_tag  :owner_name , $owner_name, :readonly => true%>
  		</p>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
  		<p>
        <%= label_tag :Owner_contact_number, nil, :class => 'floatLabel'%>
        <%= text_field_tag  :contact_number, $contact_number, :readonly => true %>
  		</p>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
      <p>
        <%= label_tag :owner_nric, nil, :class => 'floatLabel'%>
        <%= text_field_tag  :owner_nric , $owner_nric, :readonly => true%>
  		</p>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
      <p>
        <%= label_tag :township, nil, :class => 'floatLabel'%>
        <%= text_field_tag  :township , $township, :readonly => true%>
  		</p>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
      <p>
        <%= label_tag :number_of_rooms, nil, :class => 'floatLabel'%>
        <%= number_field_tag  :number_of_rooms, $number_of_rooms, :readonly => true , :class => 'number'%>
  		</p>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
      <p>
        <%= label_tag :total_pax, nil, :class => 'floatLabel'%>
        <%= number_field_tag  :total_pax, $total_pax, :readonly => true, :class => 'number'%>
  		</p>
    </div>

    <%= hidden_field_tag :condition, "receipt" %>
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
      <p>
        <%= submit_tag("Next",:class=>"btn btn-primary") %>
     </p>
    </div>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <%- end -%>
</body>

</html>

app/views/register/form.html.erb
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'index', 'data-turbolinks-track': 'reload' %>
</head>
  <body class="mybody">
    <%= form_tag(register_confirmation_path, method: "post" , local:true, class: "myform" ) do |f|%>
        <div class="col-xl-4 col-lg-6 col-lg-offset-3 col-xl-offset-4" >
          <h2 ><strong> Fill Hostel Information</strong></h2>
        </div>

      	<div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 ">
          <p>
            <%= label_tag :hostel_name, nil, :class => 'floatLabel'%>
            <%= text_field_tag  :hostel_name%>
          </p>
        </div>

        <div class="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-lg-offset-3">
      		<p>
            <%= label_tag :address, nil, :class => 'floatLabel'%>
            <%= text_area_tag  :address,"",:class => "textarea" %>
      		</p>
        </div>

        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3">
          <p>
            <%= label_tag :owner_name, nil, :class => 'floatLabel'%>
            <%= text_field_tag  :owner_name %>
      		</p>
        </div>

        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 ">
      		<p>
            <%= label_tag :Owner_contact_number, nil, :class => 'floatLabel'%>
            <%= text_field_tag  :contact_number %>
      		</p>
        </div>

        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3">
          <p>
            <%= label_tag :owner_nric, nil, :class => 'floatLabel'%>
            <%= text_field_tag  :owner_nric %>
      		</p>
        </div>

      	<div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3">
          <p>
            <%= label_tag :township, nil, :class => 'floatLabel'%>
            <%= text_field_tag  :township %>
      		</p>
        </div>

        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3">
          <p>
            <%= label_tag :number_of_rooms, nil, :class => 'floatLabel'%>
            <%= number_field_tag  :number_of_rooms,"", :class => 'number' %>
      		</p>
        </div>

        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3">
          <p>
            <%= label_tag :total_pax, nil, :class => 'floatLabel'%>
            <%= number_field_tag  :total_pax,"", :class => 'number' %>
      		</p>
        </div>

        <%= hidden_field_tag :condition, "confirm"%>
        <div class="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-lg-offset-3">
          <p>
            <%= submit_tag("Register") %>
          </p>
        </div>
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
      <%- end -%>
  </body>

</html>

app/views/register/index.html.erb
<div class="container">
      <div class="form-group myindex">
        <div class="field col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3">
          <div class="col-lg-3 col-md-3 col-sm-3">
            <%=image_tag("mylogo.png", alt: "LOGO  ", class: "myimage")%>
          </div>
         <div class="col-lg-9 col-md-9 col-sm-9">
          <h2 align="center"><strong>Hostel Self Registration System</strong></h2>
        </div>
        </div>
      </div>

      <div class="form-group col-lg-6 col-lg-offset-3 mybuttons" align="center">
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-lg-offset-2 col-xl-offset-2">
          <%= link_to t('.cancel', :default => t("helpers.links.register")),
                    register_form_path, :class => 'btn btn-primary' %>
        </div>
        <div class="col-xl-4 col-lg-4  col-md-4 col-sm-6 ">
          <%= link_to t('.cancel', :default => t("helpers.links.Check")),
                              register_check_path, :class => 'btn btn-primary' %>
        </div>
      </div>
      <div class="field col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3">
        <p align="center" style="margin-top: 20px;">
           Please enter register button for new registration <br>
           Select check button for chek older registeration<br>
           If you need any help, please enter  <a href=""> help me</a>
         </p>
      </div>
</div>

app/views/register/receipt.html.erb
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'index', 'data-turbolinks-track': 'reload' %>
</head>
<body class="mybody">
  <div class="myform">
    <div class="col-xl-4 col-lg-6 col-lg-offset-3 col-xl-offset-4">
      <h2><strong> Hostel Registration</strong></h2>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
      <p >
        <strong>
          <h5>
            Your Registration is Successful!!! <br>
            Please note  Your registrationn number!!<br>
            Your registration numbe is 12456.
          </h5>
        </strong>
      </p>
    </div>

    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-lg-offset-3 col-xl-offset-4 ">
      <%= button_tag "Download pdf", :class=>"mybtn",:style=>"font-size:14px;" %>
    </div>

    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  </div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>